name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.12.3' # Define the elixir version [required]
        otp-version: '22.3' # Define the OTP version [required]
        experimental-otp: true # as a solution for ssl library missing 
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
